### PR TITLE
Make sure we don't pop immediate in onBackStackChanged. Fixes #4

### LINKED ISSUE #4: java.lang.IllegalStateException: FragmentManager is already executing transactions
This error occurs with Support Library Version >= 25.1.0. See https://medium.com/@elye.project/new-in-support-library-25-1-0-android-disallow-commitnow-on-onbackstackchanged-227c651eefb2

### PR DESCRIPTION
**Pull request by dmfs**
Skip skipable steps right in the Transaction not in `onBackStackChanged` to make sure it doesn't crash with recent versions of the support library.

### CODE REVIEW

File: microfragments/src/main/java/org/dmfs/android/microfragments/transitions/BackTransition.java [hunk 1]
```diff
@@ -110,7 +110,15 @@ public Timestamp timestamp()
     @Override
     public void prepare(@NonNull Context context, @NonNull FragmentManager fragmentManager, @NonNull MicroFragmentHost host, @NonNull MicroFragment<?> previousStep)
     {
-        mResponseCage.pigeon(fragmentManager.popBackStackImmediate()).send(context);
+        boolean result = fragmentManager.popBackStackImmediate();
```
Comment (lemonboston) [inline microfragments/src/main/java/org/dmfs/android/microfragments/transitions/BackTransition.java:113]: Shouldn't this come after popping the skip steps? So if only "skip"s are on the backstack, then it should be `false`, right?

**Review by lemonboston — COMMENTED** [review]
Just a question: why is it needed to add the skipped steps to the backstack in the first place?

File: microfragments/src/main/java/org/dmfs/android/microfragments/transitions/BackTransition.java (hunk 1 above)
Comment (dmfs) [reply microfragments/src/main/java/org/dmfs/android/microfragments/transitions/BackTransition.java:113]: No, first we pop the current fragment but only if the backstack is non-empty.
If the next one is a "skipable" MFs (i.e a loader) we pop it an all other skipables right in front of it.

The backstack can't contain only skipables, because skipables are not added to the backstack if it's empty (because there is no need to).

Comment (lemonboston) [reply microfragments/src/main/java/org/dmfs/android/microfragments/transitions/BackTransition.java:113]: Ok, I am not sure I see these cases and the handling clearly, but it's not important at the moment.
Maybe we could spend 5 minutes on this in Dresden, easier to explain it to me in person.
